include "muxes.sk";
include "constants.sk";

StateResult atom_template(int state_1, int state_2, int state_3, int pkt_1, int pkt_2, int pkt_3, int pkt_4, int pkt_5) {
//  state_1 = Opt(state_2) + Opt(state_3);
  state_1 = Opt(state_2) / Mux3(state_3, pkt_2, C());
  StateResult ret = new StateResult();
  ret.result_state_1 = state_1;
  ret.result_state_2 = state_2;
  ret.result_state_3 = state_3;
  return ret;
}
